name: wake-surfer

include:
  - ./packages/runtime-infra/docker/compose.yml
  - ./packages/realtime-chat-database/docker/compose.yml
  - ./apps/realtime-chat-api/docker/compose.yml
  - ./apps/realtime-chat-gateway/docker/compose.yml
  - ./apps/realtime-media-gateway/docker/compose.yml
  - ./apps/web/docker/compose.yml

networks:
  default:
    internal: true
