*

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml

!apps/
!apps/auth-api/
!apps/auth-api/package.json
!apps/auth-api/prisma/
!apps/auth-api/prisma/**
!apps/auth-api/dist/
!apps/auth-api/dist/**

!packages/
!packages/oauth/
!packages/oauth/package.json
!packages/oauth/dist/
!packages/oauth/dist/**
