export const REALTIME_CHAT_ERROR_CODES = [
  "INVALID_PAYLOAD",
  "PAYLOAD_TOO_LARGE",
  "UNSUPPORTED_EVENT_TYPE",
  "UNAUTHENTICATED",
  "GATEWAY_TICKET_MISSING",
  "GATEWAY_TICKET_INVALID_OR_EXPIRED",
  "GATEWAY_TICKET_ALREADY_CONSUMED",
  "GATEWAY_SESSION_NOT_FOUND",
  "CHANNEL_ACCESS_DENIED",
  "DM_ACCESS_DENIED",
  "THREAD_ACCESS_DENIED",
  "MESSAGE_CONTENT_INVALID",
  "MESSAGE_SAVE_FAILED",
  "STREAM_NOT_FOUND",
  "API_UNAVAILABLE",
  "INTERNAL_ERROR",
] as const;

export type RealtimeChatErrorCode = (typeof REALTIME_CHAT_ERROR_CODES)[number];
